"use strict";

export const ROLEB_FETCH_PUSH_LEAD_LIST = "ROLEB_FETCH_PUSH_LEAD_LIST";

export const ROLEB_FETCHING_PUSH_LEAD_LIST = "ROLEB_FETCHING_PUSH_LEAD_LIST";

export const ROLEB_UPDATE_CURRENT_TAB = "ROLEB_UPDATE_CURRENT_TAB";
