"use strict";

export const ROLEA_FETCH_LEAD_LIST = "ROLEA_FETCH_LEAD_LIST";

export const ROLEA_FETCHING_LEAD_LIST = "ROLEA_FETCHING_LEAD_LIST";

export const ROLEA_FETCH_FILTER_DATA = "ROLEA_FETCH_FILTER_DATA";

export const ROLEA_RESET_FILTER = "ROLEA_RESET_FILTER";

export const ROLEA_FETCHING_LEAD_SOURCE = "ROLEA_FETCHING_LEAD_SOURCE";

export const ROLEA_FETCH_LEAD_SOURCE = "ROLEA_FETCH_LEAD_SOURCE";

export const ROLEA_CHECK_LEAD_CREATION = "ROLEA_CHECK_LEAD_CREATION";

export const ROLEA_CHECKING_LEAD_CREATION = "ROLEA_CHECKING_LEAD_CREATION";

export const ROLEA_POST_NEW_LEAD = "ROLEA_POST_NEW_LEAD";

export const ROLEA_POSTING_NEW_LEAD = "ROLEA_POSTING_NEW_LEAD";

export const ROLEA_FETCHING_LEAD_LIST_ERROR = "ROLEA_FETCHING_LEAD_LIST_ERROR";

export const ROLEA_RESET_CREATION_RESPONSE_STATUS = "ROLEA_RESET_CREATION_RESPONSE_STATUS";

export const ROLEA_FETCH_ENUM_LISTS = "ROLEA_FETCH_ENUM_LISTS";

export const ROLEA_FETCH_SECOND_LEAD_SOURCE_ENUM_LISTS = "ROLEA_FETCH_SECOND_LEAD_SOURCE_ENUM_LISTS";
