"use strict";

export const ROLEB_FETCHING_CONSULTANT_LIST = "ROLEB_FETCHING_CONSULTANT_LIST";

export const ROLEB_FETCH_CONSULTANT_LIST_SUCCESS = "ROLEB_FETCH_CONSULTANT_LIST_SUCCESS";

export const ROLEB_FETCH_CONSULTANT_LIST_ERROR = "ROLEB_FETCH_CONSULTANT_LIST_ERROR";
