"use strict";

export const ROLEA_FETCH_LEAD_DETAIL_LIST = "ROLEA_FETCH_LEAD_DETAIL_LIST";

export const ROLEA_FETCHING_LEAD_DETAIL_LIST = "ROLEA_FETCHING_LEAD_DETAIL_LIST";

export const ROLEA_FETCH_LEAD_DETAIL_LIST_ERROR = "ROLEA_FETCH_LEAD_DETAIL_LIST_ERROR";

export const ROLEA_SAVE_LEAD_DETAIL = "ROLEA_SAVE_LEAD_DETAIL";

export const ROLEA_SAVE_LEAD_DETAIL_ERROR = "ROLEA_SAVE_LEAD_DETAIL_ERROR";
