"use strict";

export const ROLEA_FETCH_HOME_LIST = "ROLEA_FETCH_HOME_LIST";

export const ROLEA_FETCHING_HOME_LIST = "ROLEA_FETCHING_HOME_LIST";

export const ROLEA_FETCHING_HOME_LIST_ERROR = "ROLEA_FETCHING_HOME_LIST_ERROR";

export const ROLEA_FETCH_NEWASSIGN_LIST = "ROLEA_FETCH_NEWASSIGN_LIST";

export const ROLEA_FETCHING_NEWASSIGN_LIST = "ROLEA_FETCHING_NEWASSIGN_LIST";

export const ROLEA_FETCHING_NEWASSIGN_LIST_ERROR = "ROLEA_FETCHING_NEWASSIGN_LIST_ERROR";
