export const FETCH_MESSAGE_TEMPLATE_LIST = "FETCH_MESSAGE_TEMPLATE_LIST";

export const FETCHING_MESSAGE_TEMPLATE_LIST = "FETCHING_MESSAGE_TEMPLATE_LIST";

export const SAVE_MESSAGE_TEMPLATE_LIST = "SAVE_MESSAGE_TEMPLATE_LIST";

export const SAVING_MESSAGE_TEMPLATE_LIST = "SAVING_MESSAGE_TEMPLATE_LIST";

export const FETCHING_MESSAGE_TEMPLATE_LIST_ERROR = "application.FETCHING_MESSAGE_TEMPLATE_LIST_ERROR";
