"use strict";

export const ROLEB_FETCH_LEAD_LIST = "ROLEB_FETCH_LEAD_LIST";

export const ROLEB_FETCHING_LEAD_LIST = "ROLEB_FETCHING_LEAD_LIST";

export const ROLEA_FETCHING_LEAD_LIST_ERROR = "ROLEA_FETCHING_LEAD_LIST_ERROR";

export const ROLEB_FETCH_FILTER_DATA = "ROLEB_FETCH_FILTER_DATA";

export const ROLEB_RESET_FILTER = "ROLEB_RESET_FILTER";

export const ROLEB_FETCHING_LEAD_SOURCE = "ROLEB_FETCHING_LEAD_SOURCE";

export const ROLEB_FETCH_LEAD_SOURCE = "ROLEB_FETCH_LEAD_SOURCE";

export const ROLEB_CHECK_LEAD_CREATION = "ROLEB_CHECK_LEAD_CREATION";

export const ROLEB_POST_NEW_LEAD = "ROLEB_POST_NEW_LEAD";
