"use strict";

export const ROLEC_FETCH_DRIVE_LIST = "ROLEC_FETCH_DRIVE_LIST";

export const ROLEC_FETCHING_DRIVE_LIST = "ROLEC_FETCHING_DRIVE_LIST";

export const ROLEC_FETCH_PENDING_DRIVE_LIST = "ROLEC_FETCH_PENDING_DRIVE_LIST";

export const ROLEC_FETCHING_PENDING_DRIVE_LIST = "ROLEC_FETCHING_PENDING_DRIVE_LIST";

export const ROLEC_FETCH_DRIVE_INFO = "ROLEC_FETCH_DRIVE_INFO";

export const ROLEC_FETCH_FILTER_DATA = "ROLEC_FETCH_FILTER_DATA";

export const ROLEC_RESET_FILTER = "ROLEC_RESET_FILTER";

export const ROLEC_FETCH_CAR_MANAGEMENT = "ROLEC_FETCH_CAR_MANAGEMENT";
