"use strict";

export const ROLEB_FETCHING_LEAD_DETAIL = "ROLEB_FETCHING_LEAD_DETAIL";

export const ROLEB_FETCH_LEAD_DETAIL_SUCCESS = "ROLEB_FETCH_LEAD_DETAIL_SUCCESS";

export const ROLEB_FETCH_LEAD_DETAIL_ERROR = "ROLEB_FETCH_LEAD_DETAIL_ERROR";
