"use strict";

export const ROLEB_FETCH_HOME_LIST = "ROLEB_FETCH_HOME_LIST";

export const ROLEB_FETCHING_HOME_LIST = "ROLEB_FETCH_HOME_LIST";

export const ROLEB_FETCH_HOME_LIST_ERROR = "ROLEB_FETCH_HOME_LIST_ERROR";
