"use strict";

export const ROLEA_FETCH_ACTIVITY_LIST = "ROLEA_FETCH_ACTIVITY_LIST";

export const ROLEA_FETCHING_ACTIVITY_LIST = "ROLEA_FETCHING_ACTIVITY_LIST";

export const ROLEA_FETCHING_ACTIVITY_LIST_ERROR = "ROLEA_FETCHING_ACTIVITY_LIST_ERROR";
