"use strict";

export const ROLED_FETCHING_LEAD_DETAIL = "ROLED_FETCHING_LEAD_DETAIL";

export const ROLED_FETCH_LEAD_DETAIL_SUCCESS = "ROLED_FETCH_LEAD_DETAIL_SUCCESS";

export const ROLED_FETCH_LEAD_DETAIL_ERROR = "ROLED_FETCH_LEAD_DETAIL_ERROR";
