"use strict";

export const ROLED_FETCH_LEAD_LIST = "ROLED_FETCH_LEAD_LIST";

export const ROLED_FETCHING_LEAD_LIST = "ROLED_FETCHING_LEAD_LIST";

export const ROLED_FETCH_FILTER_DATA = "ROLED_FETCH_FILTER_DATA";

export const ROLED_RESET_FILTER = "ROLED_RESET_FILTER";

export const ROLED_FETCHING_LEAD_SOURCE = "ROLED_FETCHING_LEAD_SOURCE";

export const ROLED_FETCH_LEAD_SOURCE = "ROLED_FETCH_LEAD_SOURCE";

export const ROLED_CHECK_LEAD_CREATION = "ROLED_CHECK_LEAD_CREATION";

export const ROLED_POST_NEW_LEAD = "ROLED_POST_NEW_LEAD";
