"use strict";

export const ROLED_FETCH_CONSULTANT_LIST = "ROLED_FETCH_CONSULTANT_LIST";

export const ROLED_FETCHING_CONSULTANT_LIST = "ROLED_FETCHING_CONSULTANT_LIST";

export const ROLED_FETCH_CONSULTANT_LIST_ERROR = "ROLED_FETCH_CONSULTANT_LIST_ERROR";
