"use strict";

export const ROLEA_FETCH_A_WEEK_LEAD = "ROLEA_FETCH_A_WEEK_LEAD";
export const ROLEA_FETCHED_A_WEEK_LEAD = "ROLEA_FETCHED_A_WEEK_LEAD";
export const ROLEA_FETCHING_A_WEEK_LEAD = "ROLEA_FETCHING_A_WEEK_LEAD";
export const ROLEA_FETCH_A_WEEK_LEAD_ERROR = "ROLEA_FETCH_A_WEEK_LEAD_ERROR";
