"use strict";

export const FETCH_LEAD_ACTIVITY_LIST = "FETCH_LEAD_ACTIVITY_LIST";

export const FETCHING_LEAD_ACTIVITY_LIST = "FETCHING_LEAD_ACTIVITY_LIST";

export const CREATING_LEAD_ACTIVITY = "CREATING_LEAD_ACTIVITY";

export const CREATE_LEAD_ACTIVITY_SUCCESS = "CREATE_LEAD_ACTIVITY_SUCCESS";
