"use strict";

export const ROLED_FETCH_HOME_LIST = "ROLED_FETCH_HOME_LIST";

export const ROLED_FETCHING_HOME_LIST = "ROLED_FETCH_HOME_LIST";

export const ROLED_FETCH_HOME_LIST_ERROR = "ROLED_FETCH_HOME_LIST_ERROR";
