"use strict";

export const ROLED_FETCH_APPROVE_LEAD_LIST = "ROLED_FETCH_APPROVE_LEAD_LIST";

export const ROLED_FETCHING_APPROVE_LEAD_LIST = "ROLED_FETCHING_APPROVE_LEAD_LIST";

export const ROLED_FETCH_APPROVE_LEAD_LIST_ERROR = "ROLED_FETCH_APPROVE_LEAD_LIST_ERROR";
